### ISSUE TITLE
Second level bullets not shown properly in preview

### ISSUE THREAD

**Issue by djclarke** [arundhaj/markdown-plugin#1]
I believe adding to spaces before the dash should have a bullet show as second level bullet.

Thanks for the great work.

**Comment by arundhaj** [comment]
For second level bullet, 4 space or a tab to be added.

```
* bullet 1
    * bullet 11
        * bullet 111
    * bullet 11
* bullet 2
    * bullet 21
    * bullet 21
```

let me know if the issue still persists. please attach a snapshot if required.
