### ISSUE TITLE
Needs title in the editor tab

### ISSUE THREAD

**Issue by marfire** [arundhaj/markdown-plugin#3]
Thanks for the plugin. I like that you've put the preview together with the text, controlled by the tabs at the bottom.

The only problem I see is that the text in the Editor window tab is always "Markdown Editor", so if you have multiple documents open there's no way to tell which file goes with which tab. Every other editor I've seen puts the file name (or some variation) as the tab text. As it is, this is pretty much unusable if you want to have multiple documents open at once.

**Comment by arundhaj** [comment]
Updated to show the file name in the title instead of "Markdown Editor".
